const tintColorLight = '#2f95dc';
const tintColorDark = '#fff';

export default {
  light: {
    text: '#000',
    text2: '#777676',
    textButton: '#FFFFFF',
    inputBackground: '#4F4E4E',
    inputTextColor: '#FFFFFF',
    buttonBackground: '#43BCAE',
    cancelButtonBackground: '#ABACAC',
    success: '#4a934a',
    edit: '#0275d8',
    error: '#E57373',
    border: '#DCDCDC',
    background: '#fff',
    backgroundLighter: '#fafafa',
    primary: '#D9D9D9',
    secondary: '#43BCAE',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
  },
  dark: {
    text: '#D2C2C2',
    text2: '#777676',
    textButton: '#FFFFFF',
    inputBackground: '#4F4E4E',
    inputTextColor: '#FFFFFF',
    buttonBackground: '#43BCAE',
    cancelButtonBackground: '#ABACAC',
    success: '#4a934a',
    edit: '#0275d8',
    error: '#E57373',
    border: '#333',
    background: '#1E1E1E',
    backgroundLighter: '#666',
    primary: '#43BCAE',
    secondary: '#D9D9D9',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
  },
};
