const tintColorLight = "#2f95dc";
const tintColorDark = "#fff";

const primary = "#43BCAE";
const secondary = "#69C9BE";
const tertiary = "#7143BC";

const primaryDarkColor = "#1E1E1E";
const secondaryDarkColor = "#4F4E4E";
const tertiaryDarkColor = "#5F5E5E";

const primaryDarkFontColor = "#fff";
const secondaryDarkFontColor = "#ffffff88";
const tertiaryDarkFontColor = "#ffffff78";

const primaryLightColor = "#FFFFFF";
const secondaryLightColor = "#F5F5F5";
const tertiaryLightColor = "#F0F8FF";

const white = "#fff";
const black = "#000";
const alert = "#fff";
const warning = "#fff";
const info = "#00f";
const primaryTitleLightFontColor = "#ffffff";
const primaryLightFontColor = "#000000";
const secondaryLightFontColor = "#00000088";
const tertiaryLightFontColor = "#00000078";

export default {
  light: {
    primary,
    secondary,
    tertiary,
    white,
    black,
    warning,
    alert,
    info,
    titleTextColor: "#F5F5F5",
    subtitleTextColor: "#F5F5F5",
    textColor: "#F5F5F5",
    headerBackgroundColor: primary,
    headerBackgroundBorderColor: secondaryLightColor,
    headerTextColor: white,
    bottomNavBackgroundColor: primary,
    bottomNavBackgroundBorderColor: secondaryLightColor,
    bottomNavTextColor: white,
    bottomSheetBackgroundColor: primary,
    bottomSheetBackgroundBorderColor: tertiaryLightColor,
    bottomSheetTextColor: white,
    bottomNavActiveBackgroundColor: "#F5F5F5",
    bottomNavActiveBackgroundBorderColor: "#F5F5F5",
    bottomNavActiveTextColor: "#F5F5F5",
    listItemBackgroundColor: primaryLightColor,
    listItemActiveBackgroundColor: primary,
    listItemBackgroundBorderColor: tertiaryLightColor,
    listItemTextColor: black,
    buttonActiveBackgroundColor: primary,
    buttonActiveBackgroundBorderColor: "#F5F5F5",
    buttonActiveTextColor: "#F5F5F5",
    buttonBackgroundColor: tertiaryDarkColor,
    buttonBackgroundBorderColor: "#F5F5F5",
    buttonTextColor: "#F5F5F5",
    swipeablebuttonTouchableHighlightBackgroundColor: primaryLightColor,
    swipeablebuttonBackgroundColor: primaryLightColor,
    swipeablebuttonBackgroundBorderColor: secondaryLightColor,
    swipeablebuttonTextColor: primary,
    inputBackgroundColor: white,
    inputBackgroundBorderColor: "#F5F5F5",
    inputTextColor: black,
    inputPlaceholdBackgroundColor: black,
    circleProgresBackgroundFilledColor: primary,
    circleProgresBackgroundFilledListColor: secondaryLightColor,
    circleProgresBackgroundUnfilledColor: primary,
    circleProgresBackgroundBorderColor: secondaryLightColor,
    circleProgresTextColor: black,
    circleProgresTextListColor: white,
    selectBackgroundColor: "#F5F5F5",
    selectBackgroundBorderColor: "#F5F5F5",
    selectTextColor: "#F5F5F5",
    bodyBackgroundColor: secondaryLightColor,
    bodyBackgroundBorderColor: tertiaryLightColor,
    bodyTextColor: "#F5F5F5",
    bodyAddPriceBackgroundColor: primary,
    bodyAddPriceBackgroundBorderColor: primaryLightColor,
    bodyAddPriceTextColor: primaryLightColor,
  },
  dark: {
    primary,
    secondary,
    tertiary,
    white,
    black,
    warning,
    alert,
    info,
    titleTextColor: "#4F4E4E",
    subtitleTextColor: "#4F4E4E",
    textColor: "#4F4E4E",
    headerBackgroundColor: primaryDarkColor,
    headerBackgroundBorderColor: secondaryDarkColor,
    headerTextColor: white,
    bottomNavBackgroundColor: primaryDarkColor,
    bottomNavBackgroundBorderColor: secondaryDarkColor,
    bottomNavTextColor: white,
    bottomSheetBackgroundColor: primaryDarkColor,
    bottomSheetBackgroundBorderColor: "#4F4E4E",
    bottomSheetTextColor: white,
    bottomNavActiveBackgroundColor: "#4F4E4E",
    bottomNavActiveBackgroundBorderColor: "#4F4E4E",
    bottomNavActiveTextColor: "#4F4E4E",
    listItemBackgroundColor: tertiaryDarkColor,
    listItemActiveBackgroundColor: primaryDarkColor,
    listItemBackgroundBorderColor: tertiaryDarkColor,
    listItemTextColor: "#4F4E4E",
    buttonActiveBackgroundColor: primary,
    buttonActiveBackgroundBorderColor: "#4F4E4E",
    buttonActiveTextColor: "#4F4E4E",
    buttonBackgroundColor: "#4F4E4E",
    buttonBackgroundBorderColor: "#4F4E4E",
    buttonTextColor: "#4F4E4E",
    swipeablebuttonTouchableHighlightBackgroundColor: primary,
    swipeablebuttonBackgroundColor: primaryDarkColor,
    swipeablebuttonBackgroundBorderColor: "#4F4E4E",
    swipeablebuttonTextColor: white,
    inputBackgroundColor: "#4F4E4E",
    inputBackgroundBorderColor: "#4F4E4E",
    inputTextColor: white,
    inputPlaceholdBackgroundColor: white,
    circleProgresBackgroundFilledColor: primary,
    circleProgresBackgroundFilledListColor: primaryDarkColor,
    circleProgresBackgroundUnfilledColor: primaryDarkColor,
    circleProgresBackgroundBorderColor: tertiaryDarkColor,
    circleProgresTextColor: white,
    circleProgresTextListColor: black,
    selectBackgroundColor: "#4F4E4E",
    selectBackgroundBorderColor: "#4F4E4E",
    selectTextColor: "#4F4E4E",
    bodyBackgroundColor: secondaryDarkColor,
    bodyBackgroundBorderColor: tertiaryDarkColor,
    bodyTextColor: "#4F4E4E",
    bodyAddPriceBackgroundColor: primaryDarkColor,
    bodyAddPriceBackgroundBorderColor: primaryDarkColor,
    bodyAddPriceTextColor: primaryDarkColor,
  },
  dark2: {
    white,
    black,
    warning,
    alert,
    info,
    titleTextColor: "#4F4E4E",
    subtitleTextColor: "#4F4E4E",
    textColor: "#4F4E4E",
    headerBackgroundColor: "#4F4E4E",
    headerBackgroundBorderColor: "#4F4E4E",
    headerTextColor: "#4F4E4E",
    bottomNavBackgroundColor: "#4F4E4E",
    bottomNavBackgroundBorderColor: "#4F4E4E",
    bottomNavTextColor: "#4F4E4E",
    bottomSheetBackgroundColor: "#4F4E4E",
    bottomSheetBackgroundBorderColor: "#4F4E4E",
    bottomSheetTextColor: "#4F4E4E",
    bottomNavActiveBackgroundColor: "#4F4E4E",
    bottomNavActiveBackgroundBorderColor: "#4F4E4E",
    bottomNavActiveTextColor: "#4F4E4E",
    listItemBackgroundColor: "#4F4E4E",
    listItemActiveBackgroundColor: "#4F4E4E",
    listItemBackgroundBorderColor: "#4F4E4E",
    listItemTextColor: "#4F4E4E",
    buttonActiveBackgroundColor: "#4F4E4E",
    buttonActiveBackgroundBorderColor: "#4F4E4E",
    buttonActiveTextColor: "#4F4E4E",
    buttonBackgroundColor: "#4F4E4E",
    buttonBackgroundBorderColor: "#4F4E4E",
    buttonTextColor: "#4F4E4E",
    swipeablebuttonTouchableHighlightBackgroundColor: "#4F4E4E",
    swipeablebuttonBackgroundColor: "#4F4E4E",
    swipeablebuttonBackgroundBorderColor: "#4F4E4E",
    swipeablebuttonTextColor: "#4F4E4E",
    inputBackgroundColor: "#4F4E4E",
    inputBackgroundBorderColor: "#4F4E4E",
    inputTextColor: "#4F4E4E",
    inputPlaceholdBackgroundColor: "#4F4E4E",
    circleProgresBackgroundFilledColor: "#4F4E4E",
    circleProgresBackgroundUnfilledColor: "#4F4E4E",
    circleProgresBackgroundBorderColor: "#4F4E4E",
    circleProgresTextColor: "#4F4E4E",
    selectBackgroundColor: "#4F4E4E",
    selectBackgroundBorderColor: "#4F4E4E",
    selectTextColor: "#4F4E4E",
    bodyBackgroundColor: "#4F4E4E",
    bodyBackgroundBorderColor: "#4F4E4E",
    bodyTextColor: "#4F4E4E",
  },
};
