export default [
  // {name: "Albania Lek", id: "Lek"},
  // {name: "Afghanistan Afghani", id: "؋"},
  // {name: "Argentina Peso", id: "$"},
  // {name: "Aruba Guilder", id: "ƒ"},
  // {name: "Australia Dollar", id: "$"},
  // {name: "Azerbaijan Manat", id: "₼"},
  // {name: "Bahamas Dollar", id: "$"},
  // {name: "Barbados Dollar", id: "$"},
  // {name: "Belarus Ruble", id: "Br"},
  // {name: "Belize Dollar", id: "BZ$"},
  // {name: "Bermuda Dollar", id: "$"},
  // {name: "Bolivia Bolíviano", id: "$b"},
  // {name: "Bosnia and Herzegovina Convertible Mark", id: "KM"},
  // {name: "Botswana Pula", id: "P"},
  // {name: "Bulgaria Lev", id: "лв"},
  { name: "Brazil Real", id: "R$" },
  // {name: "Brunei Darussalam Dollar", id: "$"},
  // {name: "Cambodia Riel", id: "៛"},
  // {name: "Canada Dollar", id: "$"},
  // {name: "Cayman Islands Dollar", id: "$"},
  // {name: "Chile Peso", id: "$"},
  // {name: "China Yuan Renminbi", id: "¥"},
  // {name: "Colombia Peso", id: "$"},
  // {name: "Costa Rica Colon", id: "₡"},
  // {name: "Croatia Kuna", id: "kn"},
  // {name: "Cuba Peso", id: "₱"},
  // {name: "Czech Republic Koruna", id: "Kč"},
  // {name: "Denmark Krone", id: "kr"},
  // {name: "Dominican Republic Peso", id: "RD$"},
  // {name: "East Caribbean Dollar", id: "$"},
  // {name: "Egypt Pound", id: "£"},
  // {name: "El Salvador Colon", id: "$"},
  { name: "Euro Member Countries", id: "€" },
  // {name: "Falkland Islands (Malvinas) Pound", id: "£"},
  // {name: "Fiji Dollar", id: "$"},
  // {name: "Ghana Cedi", id: "¢"},
  // {name: "Gibraltar Pound", id: "£"},
  // {name: "Guatemala Quetzal", id: "Q"},
  // {name: "Guernsey Pound", id: "£"},
  // {name: "Guyana Dollar", id: "$"},
  // {name: "Honduras Lempira", id: "L"},
  // {name: "Hong Kong Dollar", id: "$"},
  // {name: "Hungary Forint", id: "Ft"},
  // {name: "Iceland Krona", id: "kr"},
  // {name: "India Rupee", id: "₹"},
  // {name: "Indonesia Rupiah", id: "Rp"},
  // {name: "Iran Rial", id: "﷼"},
  // {name: "Isle of Man Pound", id: "£"},
  // {name: "Israel Shekel", id: "₪"},
  // {name: "Jamaica Dollar", id: "J$"},
  // {name: "Japan Yen", id: "¥"},
  // {name: "Jersey Pound", id: "£"},
  // {name: "Kazakhstan Tenge", id: "лв"},
  // {name: "Korea (North) Won", id: "₩"},
  // {name: "Korea (South) Won", id: "₩"},
  // {name: "Kyrgyzstan Som", id: "лв"},
  // {name: "Laos Kip", id: "₭"},
  // {name: "Lebanon Pound", id: "£"},
  // {name: "Liberia Dollar", id: "$"},
  // {name: "Macedonia Denar", id: "ден"},
  // {name: "Malaysia Ringgit", id: "RM"},
  // {name: "Mauritius Rupee", id: "₨"},
  // {name: "Mexico Peso", id: "$"},
  // {name: "Mongolia Tughrik", id: "₮"},
  // {name: "Moroccan-dirham", id: "د.إ"},
  // {name: "Mozambique Metical", id: "MT"},
  // {name: "Namibia Dollar", id: "$"},
  // {name: "Nepal Rupee", id: "₨"},
  // {name: "Netherlands Antilles Guilder", id: "ƒ"},
  // {name: "New Zealand Dollar", id: "$"},
  // {name: "Nicaragua Cordoba", id: "C$"},
  // {name: "Nigeria Naira", id: "₦"},
  // {name: "Norway Krone", id: "kr"},
  // {name: "Oman Rial", id: "﷼"},
  // {name: "Pakistan Rupee", id: "₨"},
  // {name: "Panama Balboa", id: "B/."},
  // {name: "Paraguay Guarani", id: "Gs"},
  // {name: "Peru Sol", id: "S/."},
  // {name: "Philippines Peso", id: "₱"},
  // {name: "Poland Zloty", id: "zł"},
  // {name: "Qatar Riyal", id: "﷼"},
  // {name: "Romania Leu", id: "lei"},
  // {name: "Russia Ruble", id: "₽"},
  // {name: "Saint Helena Pound", id: "£"},
  // {name: "Saudi Arabia Riyal", id: "﷼"},
  // {name: "Serbia Dinar", id: "Дин."},
  // {name: "Seychelles Rupee", id: "₨"},
  // {name: "Singapore Dollar", id: "$"},
  // {name: "Solomon Islands Dollar", id: "$"},
  // {name: "Somalia Shilling", id: "S"},
  // {name: "South Korean Won", id: "₩"},
  // {name: "South Africa Rand", id: "R"},
  // {name: "Sri Lanka Rupee", id: "₨"},
  // {name: "Sweden Krona", id: "kr"},
  // {name: "Switzerland Franc", id: "CHF"},
  // {name: "Suriname Dollar", id: "$"},
  // {name: "Syria Pound", id: "£"},
  // {name: "Taiwan New Dollar", id: "NT$"},
  // {name: "Thailand Baht", id: "฿"},
  // {name: "Trinidad and Tobago Dollar", id: "TT$"},
  // {name: "Turkey Lira", id: "₺"},
  // {name: "Tuvalu Dollar", id: "$"},
  // {name: "Ukraine Hryvnia", id: "₴"},
  // {name: "UAE-Dirham", id: "د.إ"},
  { name: "United Kingdom Pound", id: "£" },
  { name: "United States Dollar", id: "$" },
  // {name: "Uruguay Peso", id: "$U"},
  // {name: "Uzbekistan Som", id: "лв"},
  // {name: "Venezuela Bolívar", id: "Bs"},
  // {name: "Viet Nam Dong", id: "₫"},
  // {name: "Yemen Rial", id: "﷼"},
  // {name: "Zimbabwe Dollar", id: "Z$"}
]
