export default [
    {name: "Albania Lek", uuid: "Lek"},
    {name: "Afghanistan Afghani", uuid: "؋"},
    {name: "Argentina Peso", uuid: "$"},
    {name: "Aruba Guilder", uuid: "ƒ"},
    {name: "Australia Dollar", uuid: "$"},
    {name: "Azerbaijan Manat", uuid: "₼"},
    {name: "Bahamas Dollar", uuid: "$"},
    {name: "Barbados Dollar", uuid: "$"},
    {name: "Belarus Ruble", uuid: "Br"},
    {name: "Belize Dollar", uuid: "BZ$"},
    {name: "Bermuda Dollar", uuid: "$"},
    {name: "Bolivia Bolíviano", uuid: "$b"},
    {name: "Bosnia and Herzegovina Convertible Mark", uuid: "KM"},
    {name: "Botswana Pula", uuid: "P"},
    {name: "Bulgaria Lev", uuid: "лв"},
    {name: "Brazil Real", uuid: "R$"},
    {name: "Brunei Darussalam Dollar", uuid: "$"},
    {name: "Cambodia Riel", uuid: "៛"},
    {name: "Canada Dollar", uuid: "$"},
    {name: "Cayman Islands Dollar", uuid: "$"},
    {name: "Chile Peso", uuid: "$"},
    {name: "China Yuan Renminbi", uuid: "¥"},
    {name: "Colombia Peso", uuid: "$"},
    {name: "Costa Rica Colon", uuid: "₡"},
    {name: "Croatia Kuna", uuid: "kn"},
    {name: "Cuba Peso", uuid: "₱"},
    {name: "Czech Republic Koruna", uuid: "Kč"},
    {name: "Denmark Krone", uuid: "kr"},
    {name: "Dominican Republic Peso", uuid: "RD$"},
    {name: "East Caribbean Dollar", uuid: "$"},
    {name: "Egypt Pound", uuid: "£"},
    {name: "El Salvador Colon", uuid: "$"},
    {name: "Euro Member Countries", uuid: "€"},
    {name: "Falkland Islands (Malvinas) Pound", uuid: "£"},
    {name: "Fiji Dollar", uuid: "$"},
    {name: "Ghana Cedi", uuid: "¢"},
    {name: "Gibraltar Pound", uuid: "£"},
    {name: "Guatemala Quetzal", uuid: "Q"},
    {name: "Guernsey Pound", uuid: "£"},
    {name: "Guyana Dollar", uuid: "$"},
    {name: "Honduras Lempira", uuid: "L"},
    {name: "Hong Kong Dollar", uuid: "$"},
    {name: "Hungary Forint", uuid: "Ft"},
    {name: "Iceland Krona", uuid: "kr"},
    {name: "India Rupee", uuid: "₹"},
    {name: "Indonesia Rupiah", uuid: "Rp"},
    {name: "Iran Rial", uuid: "﷼"},
    {name: "Isle of Man Pound", uuid: "£"},
    {name: "Israel Shekel", uuid: "₪"},
    {name: "Jamaica Dollar", uuid: "J$"},
    {name: "Japan Yen", uuid: "¥"},
    {name: "Jersey Pound", uuid: "£"},
    {name: "Kazakhstan Tenge", uuid: "лв"},
    {name: "Korea (North) Won", uuid: "₩"},
    {name: "Korea (South) Won", uuid: "₩"},
    {name: "Kyrgyzstan Som", uuid: "лв"},
    {name: "Laos Kip", uuid: "₭"},
    {name: "Lebanon Pound", uuid: "£"},
    {name: "Liberia Dollar", uuid: "$"},
    {name: "Macedonia Denar", uuid: "ден"},
    {name: "Malaysia Ringgit", uuid: "RM"},
    {name: "Mauritius Rupee", uuid: "₨"},
    {name: "Mexico Peso", uuid: "$"},
    {name: "Mongolia Tughrik", uuid: "₮"},
    {name: "Moroccan-dirham", uuid: "د.إ"},
    {name: "Mozambique Metical", uuid: "MT"},
    {name: "Namibia Dollar", uuid: "$"},
    {name: "Nepal Rupee", uuid: "₨"},
    {name: "Netherlands Antilles Guilder", uuid: "ƒ"},
    {name: "New Zealand Dollar", uuid: "$"},
    {name: "Nicaragua Cordoba", uuid: "C$"},
    {name: "Nigeria Naira", uuid: "₦"},
    {name: "Norway Krone", uuid: "kr"},
    {name: "Oman Rial", uuid: "﷼"},
    {name: "Pakistan Rupee", uuid: "₨"},
    {name: "Panama Balboa", uuid: "B/."},
    {name: "Paraguay Guarani", uuid: "Gs"},
    {name: "Peru Sol", uuid: "S/."},
    {name: "Philippines Peso", uuid: "₱"},
    {name: "Poland Zloty", uuid: "zł"},
    {name: "Qatar Riyal", uuid: "﷼"},
    {name: "Romania Leu", uuid: "lei"},
    {name: "Russia Ruble", uuid: "₽"},
    {name: "Saint Helena Pound", uuid: "£"},
    {name: "Saudi Arabia Riyal", uuid: "﷼"},
    {name: "Serbia Dinar", uuid: "Дин."},
    {name: "Seychelles Rupee", uuid: "₨"},
    {name: "Singapore Dollar", uuid: "$"},
    {name: "Solomon Islands Dollar", uuid: "$"},
    {name: "Somalia Shilling", uuid: "S"},
    {name: "South Korean Won", uuid: "₩"},
    {name: "South Africa Rand", uuid: "R"},
    {name: "Sri Lanka Rupee", uuid: "₨"},
    {name: "Sweden Krona", uuid: "kr"},
    {name: "Switzerland Franc", uuid: "CHF"},
    {name: "Suriname Dollar", uuid: "$"},
    {name: "Syria Pound", uuid: "£"},
    {name: "Taiwan New Dollar", uuid: "NT$"},
    {name: "Thailand Baht", uuid: "฿"},
    {name: "Trinidad and Tobago Dollar", uuid: "TT$"},
    {name: "Turkey Lira", uuid: "₺"},
    {name: "Tuvalu Dollar", uuid: "$"},
    {name: "Ukraine Hryvnia", uuid: "₴"},
    {name: "UAE-Dirham", uuid: "د.إ"},
    {name: "United Kingdom Pound", uuid: "£"},
    {name: "United States Dollar", uuid: "$"},
    {name: "Uruguay Peso", uuid: "$U"},
    {name: "Uzbekistan Som", uuid: "лв"},
    {name: "Venezuela Bolívar", uuid: "Bs"},
    {name: "Viet Nam Dong", uuid: "₫"},
    {name: "Yemen Rial", uuid: "﷼"},
    {name: "Zimbabwe Dollar", uuid: "Z$"}
  ]
  