import GetTotalQuantityWithoutAmountByListUuidController from "./GetTotalQuantityWithoutAmountByListUuidController";
import GetTotalQuantityWithoutAmountByListUuidUseCase from "./GetTotalQuantityWithoutAmountByListUuidUseCase";
import GetListByUuid from "../GetListByUuid"
import GetListProductByUuid from "../../ListProduct/GetProductByUuid";
import GetTotalQuantityWithoutAmountByListProductUuid from "../../Amount/GetTotalQuantityWithoutAmountByListProductUuid"

const getTotalQuantityWithoutAmountByListUuidUseCase = new GetTotalQuantityWithoutAmountByListUuidUseCase(GetListByUuid, GetListProductByUuid, GetTotalQuantityWithoutAmountByListProductUuid);
const getTotalQuantityWithoutAmountByListUuidController = new GetTotalQuantityWithoutAmountByListUuidController(getTotalQuantityWithoutAmountByListUuidUseCase);

export default getTotalQuantityWithoutAmountByListUuidController;