import GetTotalQuantityWithoutAmountByListProductUuidController from "./GetTotalQuantityWithoutAmountByListProductUuidController";
import GetTotalQuantityWithoutAmountByListProductUuidUseCase from "./GetTotalQuantityWithoutAmountByListProductUuidUseCase";
import GetAmounts from "../GetAmounts"

const getTotalQuantityWithoutAmountByListProductUuidUseCase = new GetTotalQuantityWithoutAmountByListProductUuidUseCase(GetAmounts);
const getTotalQuantityWithoutAmountByListProductUuidController = new GetTotalQuantityWithoutAmountByListProductUuidController(getTotalQuantityWithoutAmountByListProductUuidUseCase);

export default getTotalQuantityWithoutAmountByListProductUuidController;